/** This class was generated by GenTest@Mobacar */
package com.arvoia.sampletask;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.web.client.RestTemplate;

@RunWith(SpringRunner.class)
@SpringBootTest
@ActiveProfiles("test")
@ContextConfiguration(classes = SampletaskApplication.class)
public class SampletaskApplicationTest {

  @Autowired
  private SampletaskApplication underTest;

  @Test
  public void testContextLoads() {
    // given
    // check if context was loaded without exception
  }

  @Test
  public void testGetRestTemplate() throws Exception {
    // given
    // when
    RestTemplate actual = underTest.getRestTemplate();
    // then
    assertNotNull(actual);
  }

}
